version: "3"
services:
    neo4j:
        container_name: neo4j
        image: neo4j:latest
        ports:
            - 7474:7474
            - 7687:7687
        env_file:
            - ./neo4j/.env
        volumes:
            - ./neo4j/neo4j_db/data:/data
            - ./neo4j/neo4j_db/logs:/logs
            - ./neo4j/neo4j_db/import:/var/lib/neo4j/import
            - ./neo4j/neo4j_db/plugins:/plugins

        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7474"]
            interval: 10s
            retries: 10
            timeout: 5s
    main:
        container_name: main
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./main/logs:/app/logs
            - ./main/files:/app/files
        env_file:
            - ./main/.env
        depends_on:
            neo4j:
                condition: service_healthy